export declare enum ACTION_STEPS {
  Redirect = 0,
  PlayStep = 1,
  WaitForCondition = 2,
  Branch = 3,
  StopWt = 4,
  Delay = 5,
  Refresh = 6,
  OpenPlayerMenu = 7,
  SetWalkMeData = 8,
  PassOwnership = 9,
  ErrorHandling = 10,
  Split = 11,
  OnPageActionClick = 12,
  OnPageActionHover = 13,
  OnPageActionFocus = 14,
  OnPageActionFillText = 15,
  OnPageActionSelectListValue = 16,
  Style = 17,
  RestartSwt = 18,
}
