export declare enum ACTIONS {
  None = 'none',
  OpenMenu = 'menu',
  OpenCoursesMenu = 'coursesMenu',
  PlayWalkthru = 'wt',
  PlayShuttle = 'shuttle',
  PlaySurvey = 'survey',
  PlayShoutOut = 'shoutout',
  PlayResource = 'resource',
  PlayContent = 'resource',
  SurveyQuestionAnswered = 'answer',
  PlayBizFlow = 'bizFlow',
  PlaySmartTipSet = 'smartTip',
  Close = 'close',
}
